### ISSUE TITLE
the code for datatset is not working

### ISSUE THREAD

**Issue by has12zen** [wenjieo/LS-YOLO#7]
![image](https://github.com/wenjieo/LS-YOLO/assets/57583693/ac6facc0-8120-482b-9a12-87dc6372b54b)

I tried the code `ycft` as mentioned in the Readme but it failed.

**Comment by wenjieo** [comment]
I'm sorry that the code is yfct. Please try it again.

**Comment by has12zen** [comment]
Thank You 😃  it is working.
